// <auto-generated />
using System;
using Ads.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ads.Migrations
{
    [DbContext(typeof(AdContext))]
    [Migration("20220527002506_AdsMigration1")]
    partial class AdsMigration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Ads.Models.Ad", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KindOfAnimal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusAd")
                        .HasColumnType("int");

                    b.Property<int>("TypeAd")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("Ads");
                });

            modelBuilder.Entity("Ads.Models.AdCoordinates", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Guid");

                    b.HasIndex("AdGuid")
                        .IsUnique();

                    b.ToTable("AdCoordinates");
                });

            modelBuilder.Entity("Ads.Models.Image", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ImageHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Guid");

                    b.HasIndex("AdGuid");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Ads.Models.AdCoordinates", b =>
                {
                    b.HasOne("Ads.Models.Ad", null)
                        .WithOne("Coordinates")
                        .HasForeignKey("Ads.Models.AdCoordinates", "AdGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ads.Models.Image", b =>
                {
                    b.HasOne("Ads.Models.Ad", null)
                        .WithMany("Photo")
                        .HasForeignKey("AdGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ads.Models.Ad", b =>
                {
                    b.Navigation("Coordinates")
                        .IsRequired();

                    b.Navigation("Photo");
                });
#pragma warning restore 612, 618
        }
    }
}
