// <auto-generated />
using System;
using Ads.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ads.Migrations
{
    [DbContext(typeof(AdContext))]
    partial class AdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Ads.Models.Ad", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoordinatesAdGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusAd")
                        .HasColumnType("int");

                    b.Property<int>("TypeAd")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.HasIndex("CoordinatesAdGuid");

                    b.ToTable("Ads");
                });

            modelBuilder.Entity("Ads.Models.AdCoordinates", b =>
                {
                    b.Property<Guid>("AdGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AdGuid");

                    b.ToTable("AdCoordinates");
                });

            modelBuilder.Entity("Ads.Models.Image", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ImageHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Guid");

                    b.HasIndex("AdGuid");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("Ads.Models.Ad", b =>
                {
                    b.HasOne("Ads.Models.AdCoordinates", "Coordinates")
                        .WithMany()
                        .HasForeignKey("CoordinatesAdGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coordinates");
                });

            modelBuilder.Entity("Ads.Models.Image", b =>
                {
                    b.HasOne("Ads.Models.Ad", null)
                        .WithMany("Photos")
                        .HasForeignKey("AdGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ads.Models.Ad", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
